HakimHC/webserver

- inc/Server.hpp
- src/main/main.cpp
- src/server/Server.cpp
This method is intended to be a debugging tool.
It prints out all of the attributes of the Server class.
> Added print() const method to Server class

- compile_flags.txt
- include/Server.hpp
- src/server/Server.cpp
Added _defaultFileDirectory and _maxClientBodySize private attributes to the Server class and renamed the include directory in the compile_flags.txt file.
> Added new private attributes to the Server class, changed compile_flags.txt

- .gitignore
Added this file in order to protect this repository, by not pushing object and executable files, in case an fclean was not done before commiting and pushing.
> Added .gitignore file (ignores object files and executable)

- src/main/main.cpp
port constructor.
Everything is working correctly. The idea of the port constructor is to test some things when the non-blocking I/O is implemented. (Educational / Debugging purposes only)
> Added second server object in main.cpp, trying out the Server class'

- Makefile
- nginx/Dockerfile
- nginx/index.html
- nginx/nginx.conf
- nginx/redirect.conf
Added a new directory to the project, for testing and educational purposes.
The directory is called 'nginx', and it contains, a Dockerfile, a couple config files and and index.html.
The idea is to test nginx behaviour with different configurations.
To build and run the test container, the syntax is the following:
make build conf=[name_of_config_file]
make run
/
make run_detach
> Added nginx directory to test HTTP/1.1 behaviour with NGINX

- nginx/two_servers.conf
New config file for the demonstration of the importance of the server_name attribute, and the 'Host' HTTP header line.
> Added new configuration file (two_servers.conf)

- include/Server.hpp
- src/main/main.cpp
- src/server/Server.cpp
creation, binding and listening, and variable initialization is now handled by a new member function: initialize().
The content of initialize() is the same as the constructor in the last commit before this one.
> Changed the Server class, the constructor is now empty and the socket

- src/request/Request.cpp
- src/server/Server.cpp
The first line of the request is being tokenized.
> Started tokenizing first line of the HTTP request message.

- include/Request.hpp
- src/request/Request.cpp
- src/server/Server.cpp
to the Request class, that prints out all its private attributes. The uri parsing is not finished yet, query strings must be parsed.
> Working on parsing of the request line. Added a print utility function

- Makefile
- src/server/Server.cpp
Issue #19 was fixed.
The issue was that an element was missing due to a missing line in the Sever defintion.
When the server accepts a client's connection, the server was not allocating memory for the new client's request buffer.
> ISSUE #19 FIXED

- src/request/Request.cpp
The parseRequestLine() method is finished.
The functionality of this function has been discussed earlier. See earlier pull requests for more information.
> Request line parsing is finished, testing done aswell.

- include/Client.hpp
- include/Request.hpp
- include/Server.hpp
- include/utils.hpp
- src/client/Client.cpp
- src/main/main.cpp
- src/request/Request.cpp
- src/server/Server.cpp
- src/utils/crlf.cpp
All of the source files and header files have been formatted (with clang-format) to the google c++ styling standard.
> Code Formatting

- include/Client.hpp
- include/Request.hpp
- include/Server.hpp
- include/utils.hpp
- src/client/Client.cpp
- src/main/main.cpp
- src/request/Request.cpp
- src/server/Server.cpp
- src/utils/crlf.cpp
The Client class has been added a private attribute: _requestBuffer, which is a string buffer of the clients request.
The Server class has been modified, the clientBuffer vector has been deleted.
This change is to unifiy the client with its respective request buffer.
> Added requestBuffer to the Client class && formatted the source files.

- Makefile
- include/HTTP.hpp
- include/Server.hpp
- src/http/HTTP.cpp
- src/main/main.cpp
- src/server/Server.cpp
This pull request contains the creation of a new HTTP class and changes made to the Server class.
The HTTP class contains a vector of all of its Server servers. The HTTP class takes care of making the servers operate. This allows us to have various servers, listening on different ports, and each one of them may have its own unique behaviour.
I believe the servers are still non-blocking this way.
> Added HTTP class that contains a vector of all of its servers.

- src/http/HTTP.cpp
The change is in HTTP.cpp. Its a small and intuitive change, 1 line added.
> Added a usleep in the main loop to lower CPU usage (HTTP.cpp).

- .gitignore
- Makefile
- src/main/main.cpp
- src/server/Location.cpp
- src/server/Location.hpp
Locations).
The Location class has a set of private attributes that are required by the subject, all of which are going to be populated by the ServerConfig's parser. The Location class offers access functions for all of its attributes (setters and getters).
The Server class will contain a vector of Locations.
> Added new Location class (the Server class will contain a vector of

- Makefile
- config.cnf
- src/http/HTTP.cpp
- src/http/HTTP.hpp
- src/main/testmain.cpp
- src/server/Location.cpp
- src/server/Location.hpp
- src/server/Server.cpp
- src/server/Server.hpp
Comente algunos metodos de las clases afectadas debido a que como los nombres de las variables cambiaron no estoy seguro que funcionen. En cualquier caso se puede retirar estos comantarios para hacer funcionar las cosas.
> Añadiendo el parseo de los archivos de configuracion.

- .gitignore
- Makefile
- include/defaults.hpp
- include/logging.hpp
- src/http/HTTP.cpp
- src/main/main.cpp
- src/request/Request.cpp
- src/request/Request.hpp
- src/response/Response.cpp
- src/response/Response.hpp
- src/server/Listener.cpp
- src/server/Listener.hpp
- src/server/Location.cpp
- src/server/Server.cpp
- src/server/Server.hpp
- webserv.conf
- www/dir/index.html
- www/first.html
New header files were added, one for logging and one for default values for the Server and Location classes. The Request class has a legacy parser, which wont be used in the future. The purpose is to start generating responses, with a simple, but not perfect request parser. The Response class is now able to generate HTML for any status code, get the current date time, and build the whole Response buffer. The design of the logic is not yet finished.
> Changes to every single class

- include/defaults.hpp
- include/logging.hpp
- include/redirection.hpp
- src/client/Client.hpp
- src/http/HTTP.cpp
- src/http/HTTP.hpp
- src/main/main.cpp
- src/main/testmain.cpp
- src/request/Request.cpp
- src/request/Request.hpp
- src/response/Response.cpp
- src/response/Response.hpp
- src/server/Listener.cpp
- src/server/Listener.hpp
- src/server/Location.cpp
- src/server/Location.hpp
- src/server/Server.cpp
- src/server/Server.hpp
- src/utils/utils.hpp
Clang-format, google style, has been passed onto all of the source / header files in the src / include directories.
> Formatted all of the source / header files.

- src/server/Location.cpp
- src/server/Location.hpp
- src/server/Server.cpp
- src/server/Server.hpp
- webserv.conf
- www/postdir/first_upload.txt
Post requests are now being accepted. It either returns a 201 if the file could be created, or a 403 if not.
> Added support for POST requests.

- .gitignore
- Makefile
- src/http/HTTP.cpp
- src/main/main.cpp
- src/server/Location.cpp
- src/server/Server.cpp
- webserv.conf
> small commit fixing parsing

- Makefile
- cgi-bin/basic.py
- config2.cnf
- include/defaults.hpp
- src/main/main.cpp
- src/server/Location.cpp
- src/server/Location.hpp
- src/server/Server.cpp
- src/server/Server.hpp
- webserv.conf
- www/cgi-bin/basic.py
> CGI primera version
